### add blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvYWxhIiwiaWQiOiI2NmJkZGFkOWM3ZDA4OWQ5Yzg3NjZjZTUiLCJpYXQiOjE3MzYxOTUwOTN9.pmpwVSn-J85vKZWYp0nhiFBL9aGL4LvqI6VoHbQ-zcA

{
    "title": "Best rockets",
    "author": "andrew",
    "url": "example.com/myblog2"
}

### like blog
POST http://localhost:3003/api/blogs/like/66c20986ad143c8649a9ad14


### add comment
POST http://localhost:5173/api/blogs/677c3c31cbe2540800c2a1e5/comments/
Content-Type: application/json

{
    "comment": "Hello world!"
}

### get blogs
GET http://localhost:3003/api/blogs/


### delete blog post
DELETE http://localhost:3003/api/blogs/66b38069127bb3d95922daa6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvYWxhIiwiaWQiOiI2NmIzODBhMTEyN2JiM2Q5NTkyMmRhYjciLCJpYXQiOjE3MjMwMzk5MTV9.VOgT-GUJCwvcMLwHAJUFfEM7LQzHOB52FjfTsXyox1I


### reset database in testing
POST http://localhost:3003/api/testing/reset


### update blog post
PUT http://localhost:3003/api/blogs/66b38069127bb3d95922daa6
Content-Type: application/json

{
    "title": "this title was changed"
}




### add user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "koala",
    "name": "KoalaIsBird",
    "password": "12345"
}


### get users
GET http://localhost:3003/api/users





### login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "koala",
    "password": "12345"
}